### ISSUE TITLE
filter Freebase suggest results based on category

### ISSUE THREAD

**Issue by jodischneider** [code4lib/shortimer#17]
When choosing Freebase items, I get lots of irrelevant stuff with the same name -- like book editions, books, musical recordings.

Does Freebase suggest allow you to specify the categories you'll accept?

If their API allows, I'd recommend filtering:

Institution fields should allow
* College/University
* Employer
* Organization
* Company
* Museum
(there may be other relevant ones but those are the ones I've encountered)

Topics fields should allow
* Programming language
* Organizational sector
* Literature subject
* Project
* Topic
(there may be other relevant ones but those are the ones I've encountered)

**Comment by edsu** [comment]
I think this was done a while ago. It will likely need adjustment though when addressing #38
