### ISSUE TITLE
Update Google authentication method

### ISSUE THREAD

**Issue by rosy1280** [code4lib/shortimer#41]
Attempts to log in to jobs.code4lib.org fail and users are redirected here: https://support.google.com/accounts/answer/6206245?p=openid&rd=1.  According to that page, OpenID 2.0 was replaced by OpenID Connect. The page also links to instructions on migrating from OpenID 2.0; those instructions can be found here: https://developers.google.com/identity/protocols/OpenID2Migration

**Comment by edsu** [comment]
I suspect that an upgrade of django-socialauth will fix this. I need to find the time to test it in a dev environment first though.

**Comment by tfmorris** [comment]
Since django-socialauth is deprecated, you might consider taking the opportunity to migrate to https://github.com/omab/python-social-auth

**Comment by edsu** [comment]
:+1:
