### ISSUE TITLE
remove job view stats 

### ISSUE THREAD

**Issue by edsu** [code4lib/shortimer#42]
They are no longer working because of Google's auth changes. I'm not sure how important they are to keep anyway. So I propose to remove them.

**Comment by jodischneider** [comment]
I think job view stats are informative to posters as well as applicants.
Maybe put on the "wishlist todos's" (not hugely important, but useful)?

**Comment by edsu** [comment]
They were good to have. But I don't have time to fix it up, and I always had slight misgivings about the stats.
