### ISSUE TITLE
Cannot log in via LinkedIn & Github

### ISSUE THREAD

**Issue by dltj** [code4lib/shortimer#44]
Try to log in via `http://jobs.code4lib.org/login/linkedin/?next=/curate/` URL.  I get a page back a 404-not-found status code.

**Comment by edsu** [comment]
Yes, Github is broken too. I guess I'll just disable them until they work again.

**Comment by dltj** [comment]
Thanks, Ed.  I can get in via Twitter, so all is well with me...

**Comment by edsu** [comment]
Disabled these, since Twitter, Facebook and Google seem to be good enough.
